runtime: java
env: flex
threadsafe: true
manual_scaling:
 instances: 1
service: citiesrest
handlers:
 - url: /.*
   script: this field is required, but ignored
resources:
    cpu: 1
    memory_gb: 2.3
    disk_size_gb: 10
    volumes:
    - name: ramdisk1
      volume_type: tmpfs
      size_gb: 0.5